name: CI with coverage data

on:
  pull_request:

env:
  MIX_ENV: "test"

jobs:
  ci-run:
    runs-on: [ubuntu-22.04]
    name: Elixir CI

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Erlang/OTP with Elixir and mix
        uses: erlef/setup-beam@v1
        with:
          otp-version: "26.2"
          elixir-version: "1.16"

      - run: "mix deps.get"
      - run: "mix compile"
      - run: "mix test --cover"

      - name: Code Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          format: markdown
          badge: true
          thresholds: '60 80'
          output: both

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
