name: CI with coverage data

on:
  push:

env:
  MIX_ENV: "test"

jobs:
  ci-run:
    runs-on: [ubuntu-22.04]
    name: Elixir CI

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Erlang/OTP with Elixir and mix
        uses: erlef/setup-beam@v1
        with:
          otp-version: "26.2"
          elixir-version: "1.16"

      - run: "mix deps.get"
      - run: "mix compile"
      - run: "mix test --cover"
