name: CI with coverage data

on:
  pull_request:
    branches: [main]

env:
  MIX_ENV: "test"

jobs:
  ci-run:
    runs-on: [docker]
    name: Elixir CI
    strategy:
      matrix:
        otp: ["26.2"]
        elixir: ["1.16"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Erlang/OTP with Elixir and mix
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - run: "mix deps.get"
      - run: "mix compile"
      - run: "mix test --cover"
