name: CI with coverage data

on:
  pull_request:

env:
  MIX_ENV: "test"

jobs:
  ci-run:
    runs-on: [ubuntu-22.04]
    name: Elixir CI

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Erlang/OTP with Elixir and mix
        uses: erlef/setup-beam@v1
        with:
          otp-version: "26.2"
          elixir-version: "1.16"

      - run: "mix deps.get"
      - run: "mix compile"
      - run: "mix test --cover"

      - name: Print cobertura report
        uses: 5monkeys/cobertura-action@v14
        with:
          path: apps/*/coverage.xml
          minimum_coverage: 80
          only_changed_files: true
          show_missing: true
          skip_covered: false
          link_missing_lines: true
