name: CI with coverage data

on:
  pull_request:

env:
  MIX_ENV: "test"

jobs:
  ci-run:
    runs-on: [ubuntu-22.04]
    name: Elixir CI

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Erlang/OTP with Elixir and mix
        uses: erlef/setup-beam@v1
        with:
          otp-version: "26.2"
          elixir-version: "1.16"

      - run: "mix deps.get"
      - run: "mix compile"
      - run: "mix test --cover"

      - name: Son coverage
        uses: 5monkeys/cobertura-action@v14
        with:
          path: apps/son_app/coverage.xml
          minimum_coverage: 80
          report_name: "apps/son_app coverage"
          show_missing: true
          link_missing_lines: true
          link_missing_lines_source_dir: apps/son_app

      - name: Daughter coverage
        uses: 5monkeys/cobertura-action@v14
        with:
          path: apps/daughter_app/coverage.xml
          report_name: "apps/daughter_app coverage"
          minimum_coverage: 80
          show_missing: true
          link_missing_lines: true
          link_missing_lines_source_dir: apps/daughter_app
